add styles for biography-section
Vereshchagina/otus-css-vereshchagina pull request #4
Opened 2023-05-04 18:06 UTC by Vereshchagina

2023-05-08 15:06 UTC, lipa88-mk requested changes
Очень хорошая работа! Пару комментариев с улучшениями написала ниже, посмотрите пожалуйста. И если будут вопросы - пишите)

2023-05-08 15:06 UTC, lipa88-mk commented on index.html
> +                <h2 class="biography__author">Katya
С точки зрения семантики - секция Биографии, в которой говорится про Катю Милс. То есть уровни заголовков должны быть другие, наоборот. 

Дополнительно:  с точки зрения семантики секции желательно, чтобы заголовок 2 уровня был первым. Попробуйте поставить его в разметке строчкой выше, и с помощью возможностей флексов отобразить после картинки.

2023-05-08 15:06 UTC, lipa88-mk commented on index.html
> +                <h3 class="biography__subtitle">Art Director
А это уже не заголовок, а просто текст. И даже 2 разных, тк Art Director - это ее должность, а остальное - список скилов.

2023-05-08 15:06 UTC, lipa88-mk commented on index.html
>                  <img class="biography__decor" src="./images/rectangle.png" alt="Decorative line.">
Любые декоративные элементы добавляются с помощью css, не картинкой) Это маленький черный прямоугольник, который можно создать стилями и добавить с помощью псевдоэлемента before к цитате ниже, тк он именно к цитате и относится.

2023-05-08 15:06 UTC, lipa88-mk commented on style/style.css
> +.biography__title{
Для десктопа расположение относительное+абсолютное получается точно на месте, но при уменьшении ширины страницы заголовок секции уезжает: 
![image](https://user-images.githubusercontent.com/65017545/236859805-76fd1b93-5613-4589-a94f-d59a5d80d58f.png)

Попробуйте расположить элементы без позиционирования, только на флексах. Для текста справа вполне удобно было бы использовать какую-то обертку, чтобы было удобнее.

2023-05-08 21:22 UTC, Vereshchagina commented on style/style.css
> +.biography__title{
К сожалению, по макету непонятно, как ведет себя заголовок. Возможно он отъезжает, т.к. в блоке ниже заголовок находится посерениде. А может и не отъезжает. Вот как тут понять?

2023-05-08 21:24 UTC, Vereshchagina commented on index.html
> +                <h2 class="biography__author">Katya
Не совсем поняла, что значит предложение "С точки зрения семантики - секция Биографии, в которой говорится про Катю Милс." Что с секцией с точки зрения семантики?

2023-05-11 19:07 UTC, lipa88-mk commented on style/style.css
> +.biography__title{
Самое простое - задать вопрос на ближайшем вебинаре либо в чате группы в ТГ :)

2023-05-11 19:10 UTC, lipa88-mk commented on index.html
> +                <h2 class="biography__author">Katya
Какой заголовок главный, а какой его дополняет и уточняет? Сначала это секция биографии, а уже потом кого именно это биография, тк Кати Милс. Поэтому уровни заголовков должны быть другие

2023-05-11 19:26 UTC, Vereshchagina commented on index.html
> +                <h2 class="biography__author">Katya
Теперь понятно, спасибо большое!

2023-05-13 09:09 UTC, lipa88-mk commented
Да, теперь все ужимается очень хорошо) Ну и еще чуть-чуть) Для выравнивания по вертикали у `biography__content` вместо марджинов можно так же использовать свойства флекс-элемента, например `align-self: center;`. 
И секция будет ужиматься еще аккуратнее: 
![image](https://github.com/Vereshchagina/otus-css-vereshchagina/assets/65017545/9618c2e7-f0a1-42a4-93ea-c46807d72ed5)
Картинка плющится, но с ней мы еще будем работать дальше)

2023-05-13 12:38 UTC, merged